# Generated by Django 5.1.1 on 2024-10-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atlanta_Restaurant_Finder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='name',
        ),
    ]
