# Generated by Django 5.1.1 on 2024-10-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atlanta_Restaurant_Finder', '0002_remove_favorite_created_at_remove_favorite_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='place_id',
            field=models.TextField(),
        ),
    ]
